# Generated by Django 4.2.23 on 2025-09-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='empty', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='empty', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='empty', max_length=16),
        ),
    ]
