# Generated by Django 4.2.23 on 2025-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_height',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_width',
            field=models.IntegerField(blank=True, default=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='empty', height_field='profile_height', upload_to=None, width_field='profile_width'),
        ),
    ]
