# Generated by Django 4.2.23 on 2025-09-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_profile_profile_height_profile_profile_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='empty', height_field='profile_height', upload_to='profile_pic', width_field='profile_width'),
        ),
    ]
