# Generated by Django 4.2.23 on 2025-09-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_profile_profile_picture'),
    ]

    operations = [
    ]
