# Generated by Django 4.2.23 on 2025-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_role_alter_lesson_teacher_alter_reservation_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pic/01.jpg', height_field='profile_height', upload_to='profile_pic', width_field='profile_width'),
        ),
    ]
