# Generated by Django 4.2.23 on 2025-11-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='classroom_lesson',
        ),
    ]
