# Generated by Django 4.2.23 on 2025-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_alter_lesson_options_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelTable(
            name='lesson',
            table=None,
        ),
    ]
