# Generated by Django 4.2.23 on 2025-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_lesson_options_alter_lesson_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(default='oyunbold', max_length=30),
        ),
    ]
