# Generated by Django 4.2.23 on 2025-11-02 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
