# Generated by Django 4.2.23 on 2025-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_lesson_lesson_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_types',
        ),
    ]
