# Generated by Django 4.2.23 on 2025-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_remove_lesson_lesson_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
    ]
