# Generated by Django 4.2.23 on 2025-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_lessontypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontypes',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
