# Generated by Django 4.2.23 on 2025-11-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_lessontypes_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
