# Generated by Django 4.2.23 on 2025-11-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_alter_reservation_options_alter_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_duration',
            field=models.IntegerField(default=60),
        ),
    ]
