# Generated by Django 5.2.7 on 2025-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_reservation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='student', max_length=20, unique=True),
        ),
    ]
