# Generated by Django 5.2.7 on 2025-11-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_alter_role_display_name_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.ForeignKey(blank=True, default='student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.role'),
        ),
    ]
